### ISSUE TITLE
NPE on "204 - no content"-response with OpenAPI generated Jersey client

### ISSUE THREAD

**Issue by GTaenzer** [intershop/iom-test-framework#44] opened 2023-01-12 08:57 UTC
**Affected version**
4.4.0

**Actual behavior**
Generated deleteReservation request in ReservationServiceHandler fails with NPE on 204:
Exception during FilterChain execution
java.lang.NullPointerException: Cannot invoke "org.glassfish.grizzly.http.HttpRequestPacket.getProcessingState()" because the return value of "org.glassfish.grizzly.http.HttpClientFilter$ClientHttpResponseImpl.getRequest()" is null
	at org.glassfish.grizzly.http.HttpClientFilter$ClientHttpResponseImpl.getProcessingState(HttpClientFilter.java:644)

**Expected behavior**
empty body should be ok for 204 responses

**To Reproduce**
1. create a reservation
2. try to delete the reservation using deleteReservation request in ReservationServiceHandler

AB#82534

**Comment by jo-phil** [comment] 2024-02-15 10:13
duplicate of #91

**Closed as not planned** 2024-02-15 10:13 UTC
Labels: bug
